/*
    --  INTEGRANTES--
  Jo�o Victor Michaeli : 555678
  Vinicius Saes : 554456
*/





-- DROPS
/*
DROP TABLE tbl_servicos;
DROP TABLE tbl_mecanicas;
DROP TABLE tbl_funcionarios;
DROP TABLE tbl_diagnosticos;
DROP TABLE tbl_veiculos;
DROP TABLE tbl_modelo;
DROP TABLE tbl_clientes;
DROP TABLE tbl_cadastro;
*/



-- TABELA CADASTRO
CREATE TABLE tbl_cadastro (
id_cadastro INTEGER GENERATED BY DEFAULT AS IDENTITY,
usuario VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
telefone CHAR(14) NOT NULL,
senha VARCHAR(16) NOT NULL,
nome VARCHAR(30) NOT NULL,
cpf VARCHAR(11) NOT NULL,
rua VARCHAR(100) NOT NULL,
numero SMALLINT NOT NULL,
complemento VARCHAR(20),
bairro VARCHAR(50) NOT NULL,
cep CHAR(8) NOT NULL,
estado CHAR(2) NOT NULL,
cidade VARCHAR(70) NOT NULL,
tipo CHAR(1) NOT NULL,

CONSTRAINT tbl_cadastro_pk PRIMARY KEY (id_cadastro),
CONSTRAINT tbl_cadastro_un UNIQUE (usuario,email,telefone)
);


INSERT INTO tbl_cadastro(usuario, email, telefone, senha, nome,cpf, rua, numero, complemento, bairro, cep, estado, cidade, tipo)
    VALUES ('joaovictor123', 'joao.victor@email.com', '11987654321', 'senhaSegura123', 'Jo�o Victor','91562032097', 'Rua das Flores', '123', 'Apt 45', 'Centro', '01234567', 'SP', 'S�o Paulo', 'c');
INSERT INTO tbl_cadastro(usuario, email, telefone, senha, nome,cpf, rua, numero, complemento, bairro, cep, estado, cidade, tipo)
    VALUES ('mariasilva88', 'maria.silva@email.com', '21987654321', 'senhaForte2024', 'Maria da Silva','81556638094', 'Avenida Paulista', '456', 'Bloco B', 'Bela Vista', '01311000', 'SP', 'S�o Paulo', 'c');
INSERT INTO tbl_cadastro(usuario, email, telefone, senha, nome,cpf, rua, numero, complemento, bairro, cep, estado, cidade, tipo)
    VALUES ('carlosjunior90', 'carlos.junior@email.com', '31976543210', 'senhaSegura2024', 'Carlos Junior','20887668046', 'Rua das Palmeiras', '789', 'Casa', 'Vila Nova', '31560000', 'MG', 'Belo Horizonte', 'f');
INSERT INTO tbl_cadastro(usuario, email, telefone, senha, nome,cpf, rua, numero, complemento, bairro, cep, estado, cidade, tipo)
    VALUES ('anaoliveira22', 'ana.oliveira@email.com', '11999887766', 'minhaSenha2024', 'Ana Oliveira','85345366004', 'Rua dos Pinheiros', '101', 'Apt 12', 'Jardim Paulista', '01419001', 'SP', 'S�o Paulo', 'f');


SELECT * FROM tbl_cadastro;



-- TABELA CLIENTES
CREATE TABLE tbl_clientes(
id_cadastro INTEGER NOT NULL,
id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY,

CONSTRAINT tbl_clientes_pk PRIMARY KEY (id_cadastro),
CONSTRAINT tbl_clientes_un UNIQUE (id_cliente),
CONSTRAINT cliente_id_cadastro_fk FOREIGN KEY (id_cadastro)
    REFERENCES tbl_cadastro (id_cadastro)
);

INSERT INTO tbl_clientes(id_cadastro)
    VALUES(1);
INSERT INTO tbl_clientes(id_cadastro)
    VALUES(2);
    
    
SELECT * FROM tbl_clientes;



-- TABELA MODELO
CREATE TABLE tbl_modelo(
modelo VARCHAR(30),
marca VARCHAR(30) NOT NULL,
ano SMALLINT NOT NULL,
quilometragem INTEGER NOT NULL,

CONSTRAINT tbl_modelo_pk PRIMARY KEY (modelo)
);


INSERT INTO tbl_modelo(modelo,marca,ano,quilometragem)
    VALUES('Civic Si','Honda',2018,80000);
INSERT INTO tbl_modelo(modelo,marca,ano,quilometragem)
    VALUES('Lancer Evo IX','Mitsubishi',2000,140000);

SELECT * FROM tbl_modelo;



-- TABELA VEICULOS
CREATE TABLE tbl_veiculos (
placa CHAR(7) NOT NULL,
id_cliente INTEGER NOT NULL,
modelo VARCHAR(30) NOT NULL,
dono VARCHAR(30) NOT NULL,

CONSTRAINT tbl_veiculos_pk PRIMARY KEY (placa),
CONSTRAINT id_veiculo_cliente_fk FOREIGN KEY (id_cliente)
    REFERENCES tbl_clientes (id_cliente),
CONSTRAINT id_veiculo_modelo_fk FOREIGN KEY (modelo)
    REFERENCES tbl_modelo (modelo)
);

INSERT INTO tbl_veiculos (placa, id_cliente, modelo, dono)
    VALUES ('ABC1234', 1, 'Civic Si', 'Jo�o Victor');
INSERT INTO tbl_veiculos (placa, id_cliente, modelo, dono)
    VALUES ('XYZ9876', 2, 'Lancer Evo IX', 'Maria Silva');

    
SELECT * FROM tbl_veiculos;



-- TABELA DIAGNOSTICOS
CREATE TABLE tbl_diagnosticos(
id_diagnostico INTEGER GENERATED BY DEFAULT AS IDENTITY,
placa CHAR(7) NOT NULL,
problema_veiculo VARCHAR(100) NOT NULL,
relatorio VARCHAR(150) NOT NULL,

CONSTRAINT tbl_diagnosticos_pk PRIMARY KEY (id_diagnostico),
CONSTRAINT placa_fk FOREIGN KEY (placa)
    REFERENCES tbl_veiculos (placa)
);

INSERT INTO tbl_diagnosticos(id_diagnostico,placa,problema_veiculo,relatorio)
    VALUES(1,'ABC1234','Barulho roda dianteira esquerda','Carro apresentando barulho na roda dianteira esquerda ao passar por trepida��es');
INSERT INTO tbl_diagnosticos(id_diagnostico,placa,problema_veiculo,relatorio)
    VALUES(2,'XYZ9876','Baixa press�o','Carro apresentando fraqueza ao ultrapassar 3000 rpm');
    
SELECT * FROM tbl_diagnosticos;



-- TABELA FUNCIONARIOS
CREATE TABLE tbl_funcionarios (
id_cadastro INTEGER NOT NULL,
id_funcionario INTEGER GENERATED BY DEFAULT AS IDENTITY,
cargo VARCHAR(30) NOT NULL,

CONSTRAINT tbl_funcionarios_pk PRIMARY KEY (id_cadastro),
CONSTRAINT tbl_funcionarios_un UNIQUE (id_funcionario),
CONSTRAINT funcionario_id_cadastro_fk FOREIGN KEY (id_cadastro)
    REFERENCES tbl_cadastro (id_cadastro)
);

INSERT INTO tbl_funcionarios(id_cadastro,cargo)
    VALUES(3,'gerente');
INSERT INTO tbl_funcionarios(id_cadastro,cargo)
    VALUES(4,'secretaria');   

SELECT * FROM tbl_funcionarios;



-- TABELA MECANICAS
CREATE TABLE tbl_mecanicas (
id_mecanica INTEGER GENERATED BY DEFAULT AS IDENTITY,
telefone CHAR(11) NOT NULL,
email VARCHAR(50) NOT NULL,
id_funcionario INTEGER NOT NULL,
nome VARCHAR(30) NOT NULL,
rua VARCHAR(100) NOT NULL,
numero SMALLINT NOT NULL,
bairro VARCHAR(50) NOT NULL,
cep CHAR(8) NOT NULL,
cidade VARCHAR(70) NOT NULL,
estado CHAR(2) NOT NULL,

CONSTRAINT tbl_mecanicas_pk PRIMARY KEY (id_mecanica),
CONSTRAINT tbl_mecanicas_un UNIQUE (telefone,email),
CONSTRAINT id_funcionario_fk FOREIGN KEY (id_funcionario)
    REFERENCES tbl_funcionarios (id_funcionario)
);

INSERT INTO tbl_mecanicas(telefone,email,id_funcionario,nome,rua,numero,bairro,cep,cidade,estado)
    VALUES('11998123456','mecanica1@gmail.com',1,'Mecanica Tomas Turbo','Jardim das flores',185,'S�o Miguel',01123000,'S�o Paulo','SP');
INSERT INTO tbl_mecanicas(telefone,email,id_funcionario,nome,rua,numero,bairro,cep,cidade,estado)
    VALUES('11998223345','mecanica2@gmail.com',2,'Mecanica Tiao','Av. Laranja',222,'Colina',01123111,'S�o Paulo','SP');
    
SELECT * FROM tbl_mecanicas;



-- TABELA SERVICOS
CREATE TABLE tbl_servicos (
id_servico INTEGER GENERATED BY DEFAULT AS IDENTITY,
id_mecanica INTEGER NOT NULL,
id_cliente INTEGER NOT NULL,
data_conserto DATE NOT NULL,
inicio_servico TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
fim_servico TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
pecas_trocadas VARCHAR(100) NOT NULL,
descricao VARCHAR(200) NOT NULL,

CONSTRAINT tbl_servicos_pk PRIMARY KEY (id_servico),
CONSTRAINT tbl_servicos_mecanica_fk FOREIGN KEY (id_mecanica)
    REFERENCES tbl_mecanicas (id_mecanica),
CONSTRAINT tbl_servicos_cliente_fk FOREIGN KEY (id_cliente)
    REFERENCES tbl_clientes (id_cliente)
);

INSERT INTO tbl_servicos(id_mecanica,id_cliente,data_conserto,inicio_servico,fim_servico,pecas_trocadas,descricao)
    VALUES(1,1,DATE '2024-08-31',TIMESTAMP '2024-08-31 13:30:23',TIMESTAMP '2024-08-31 17:20:14','Filtro de oleo + 4 litros de oleo','Troca de oleo e filtro em uma Fiat Touro');
INSERT INTO tbl_servicos(id_mecanica,id_cliente,data_conserto,inicio_servico,fim_servico,pecas_trocadas,descricao)
    VALUES(2,2,DATE '2024-09-01',TIMESTAMP '2024-09-01 09:00:19',TIMESTAMP '2024-09-01 14:15:44','n/a','Revis�o na caixa de transmiss�o Fiat Touro');

SELECT * From tbl_servicos;