CREATE TABLE tbl_cadastro (
id_cadastro INTEGER GENERATED BY DEFAULT AS IDENTITY,
usuario VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
telefone CHAR(14) NOT NULL,
senha VARCHAR(16) NOT NULL,
nome VARCHAR(30) NOT NULL,
rua VARCHAR(100) NOT NULL,
numero SMALLINT NOT NULL,
complemento VARCHAR(20),
bairro VARCHAR(50) NOT NULL,
cep CHAR(8) NOT NULL,
estado CHAR(2) NOT NULL,
cidade VARCHAR(70) NOT NULL,
tipo CHAR(1) NOT NULL,

CONSTRAINT tbl_cadastro_pk PRIMARY KEY (id_cadastro),
CONSTRAINT tbl_cadastro_un UNIQUE (usuario,email,telefone)
);



CREATE TABLE tbl_clientes(
id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY,
id_cadastro INTEGER,
cpf CHAR(14) NOT NULL,

CONSTRAINT tbl_clientes_pk PRIMARY KEY (id_cliente),
CONSTRAINT cliente_id_cadastro_fk FOREIGN KEY (id_cadastro)
    REFERENCES tbl_cadastro (id_cadastro),
CONSTRAINT tbl_clientes_un UNIQUE (cpf)
);



CREATE TABLE tbl_veiculos(
placa CHAR(7),
id_cliente INTEGER NOT NULL,
dono VARCHAR(30) NOT NULL,
modelo VARCHAR(30) NOT NULL,
fabricante VARCHAR(30) NOT NULL,
ano SMALLINT NOT NULL,
quilometragem_atual INTEGER NOT NULL,

CONSTRAINT tbl_veiculos_pk PRIMARY KEY (placa),
CONSTRAINT tbl_veiculos_fk FOREIGN KEY (id_cliente)
    REFERENCES tbl_clientes (id_cliente)
);
    


CREATE TABLE tbl_mecanicas(
id_mecanica INTEGER GENERATED BY DEFAULT AS IDENTITY,
id_cadastro INTEGER,
cnpj VARCHAR(14) NOT NULL,

CONSTRAINT tbl_mecanica_pk PRIMARY KEY (id_mecanica),
CONSTRAINT mecanica_id_cadastro_fk FOREIGN KEY (id_cadastro)
    REFERENCES tbl_cadastro (id_cadastro),
CONSTRAINT tbl_mecanica_un UNIQUE (cnpj)
);



CREATE TABLE tbl_servicos(
id_servico INTEGER GENERATED BY DEFAULT AS IDENTITY,
descricao VARCHAR(200) NOT NULL,
categoria_servico VARCHAR(100) NOT NULL,
valor_servico DECIMAL(7,2) NOT NULL,

CONSTRAINT tbl_servicos_pk PRIMARY KEY (id_servico)
);



CREATE TABLE tbl_servicos_cadastrados (
id_servico_agendado INTEGER GENERATED BY DEFAULT AS IDENTITY,
id_mecanica INTEGER,
id_servico INTEGER,

CONSTRAINT tbl_servicos_cadastrados_pk PRIMARY KEY (id_servico_agendado),
CONSTRAINT tbl_servicos_mecanica_fk FOREIGN KEY (id_mecanica)
    REFERENCES tbl_mecanicas(id_mecanica),
CONSTRAINT tbl_servicos_servico_fk FOREIGN KEY (id_servico)
    REFERENCES tbl_servicos(id_servico),
CONSTRAINT tbl_servicos_cadastrados_un UNIQUE (id_mecanica, id_servico)
);



CREATE TABLE tbl_agendamentos (
id_agendamento INTEGER GENERATED BY DEFAULT AS IDENTITY,
placa CHAR(7),
data_agendamento DATE,

CONSTRAINT tbl_agendamentos_pk PRIMARY KEY (id_agendamento),
CONSTRAINT tbl_agendamentos_placa_fk FOREIGN KEY (placa)
    REFERENCES tbl_veiculos (placa)
);