CREATE TABLE tbl_cadastros (
id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY,
login VARCHAR(30) NOT NULL,
senha VARCHAR(16) NOT NULL,
cep VARCHAR(8) NOT NULL,
logradouro VARCHAR(100),
bairro VARCHAR(100),
localidade VARCHAR(100),
uf VARCHAR(100),

CONSTRAINT tbl_cadastros_pk PRIMARY KEY (id_cliente)
);

CREATE TABLE tbl_veiculos (
placa VARCHAR(7) NOT NULL,
id_cliente INTEGER NOT NULL,
modelo VARCHAR(100) NOT NULL,

CONSTRAINT tbl_veiculos_placa_pk PRIMARY KEY (placa),
CONSTRAINT tbl_veiculos_cliente_fk FOREIGN KEY (id_cliente)
    REFERENCES tbl_cadastros (id_cliente)
);

CREATE TABLE tbl_agendamentos (
id_agendamento INTEGER GENERATED BY DEFAULT AS IDENTITY,
id_cliente INTEGER NOT NULL,
servico VARCHAR(200) NOT NULL,
data_agendamento DATE NOT NULL,
hora TIMESTAMP NOT NULL,

CONSTRAINT tbl_agendamentos_pk PRIMARY KEY (id_agendamento),
CONSTRAINT tbl_agendamento_cliente FOREIGN KEY (id_cliente)
    REFERENCES tbl_cadastros (id_cliente)
);
